services:
  app:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: bank-app
    expose:
      - "8001"
      - "11001"
    networks:
      - deploy_net
    volumes:
      - deploy_sqlite_dir:/data
    working_dir: /app

networks:
  deploy_net:
    external: true

volumes:
  deploy_sqlite_dir: 
    external: true
