// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package schema

import (
	"database/sql"
)

type Account struct {
	ID        sql.NullInt64
	FirstName sql.NullString
	LastName  sql.NullString
	Username  sql.NullString
	Email     sql.NullString
	Password  sql.NullString
	Balance   sql.NullFloat64
}

type Transaction struct {
	ID        sql.NullInt64
	Sender    interface{}
	Receiver  interface{}
	Amount    sql.NullFloat64
	Timestamp interface{}
}
